CREATE TABLE `customerSamples` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`orderID` varchar(64) NOT NULL,
	`trackingId` varchar(64),
	`fluteType` varchar(64) NOT NULL,
	`sizeW` int NOT NULL,
	`sizeL` int NOT NULL,
	`bqComment` text NOT NULL,
	`currentQty` int NOT NULL,
	`customerName` varchar(256) NOT NULL,
	`remark` text,
	`deliveryMold` enum('send_to_pp1','custom') NOT NULL,
	`deliveryMoldCustom` varchar(256),
	`status` enum('pending','progress','delivery') NOT NULL DEFAULT 'pending',
	`requestedBy` varchar(64) NOT NULL,
	`workerName` varchar(128) NOT NULL,
	`progressBy` varchar(128),
	`progressAt` timestamp,
	`deliveryBy` varchar(128),
	`deliveryAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customerSamples_id` PRIMARY KEY(`id`)
);
